# Generated by Django 3.0.4 on 2020-05-14 12:42

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transac',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transac',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
