# Generated by Django 3.0.4 on 2020-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200515_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceeding',
            name='bibtex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='customerid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
