# Generated by Django 3.0.4 on 2020-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200521_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='fee',
            field=models.BooleanField(default=False, verbose_name='Participants must pay a fee?'),
        ),
        migrations.AddField(
            model_name='createconf',
            name='fee_amount',
            field=models.FloatField(default=0.0, null=True, verbose_name='Fee they must pay'),
        ),
        migrations.AddField(
            model_name='createconf',
            name='fee_currency',
            field=models.CharField(default='EUR', max_length=10, verbose_name='In which currency?'),
        ),
    ]
