# Generated by Django 3.0.4 on 2020-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20200528_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='fee_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fee they must pay'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='fee_currency',
            field=models.CharField(blank=True, default='EUR', max_length=10, null=True, verbose_name='In which currency?'),
        ),
    ]
