# Generated by Django 3.0.4 on 2020-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20200528_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='haspaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transac',
            name='isparticipantfee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='fee_currency',
            field=models.CharField(blank=True, choices=[('Euros', 'Euros'), ('US Dollars', 'US Dollars'), ('GB Pounds', 'GB Pounds')], default='Euros', max_length=15, null=True, verbose_name='In which currency?'),
        ),
    ]
