# Generated by Django 3.0.4 on 2020-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20200529_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='free',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
