# Generated by Django 3.0.4 on 2020-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_registerconf_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='accountnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bicswiftcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='rootingnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='sortcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
