# Generated by Django 3.0.4 on 2020-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20200529_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bankcountry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bankusername',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
