# Generated by Django 3.0.4 on 2020-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20200529_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registerconf',
            name='idconf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registerconf',
            name='mp4_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='registerconf',
            name='recidconf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerconf',
            name='rectalk',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='accountnumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bankcountry',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bankusername',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of bank account owner (you or your institute)'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bicswiftcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BIC/Swift code'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rootingnumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rooting number'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='sortcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sort code'),
        ),
    ]
