# Generated by Django 3.0.4 on 2020-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20200605_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='mp4_url_bm',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
