# Generated by Django 3.0.4 on 2020-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_registerconf_mp4_url_bm'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='recid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
