# Generated by Django 3.0.4 on 2020-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20200713_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='showprogram',
            field=models.BooleanField(default=False, verbose_name='Program ready to be displayed on the conference website?'),
        ),
    ]
