# Generated by Django 3.0.4 on 2020-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_createvisio_vimeo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='poster_invite_chat_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
