# Generated by Django 3.0.4 on 2020-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_registerconf_poster_invite_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
