# Generated by Django 3.0.4 on 2020-07-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20200720_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='transac',
            name='vat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
