# Generated by Django 3.0.4 on 2020-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_transac_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='daughterconf',
            field=models.BooleanField(default=False, verbose_name='Or are you creating a session for a master conference that is already created?'),
        ),
        migrations.AddField(
            model_name='createconf',
            name='masterconf',
            field=models.BooleanField(default=False, verbose_name='Are you creating the master conference?'),
        ),
        migrations.AddField(
            model_name='createconf',
            name='masterconfpass',
            field=models.IntegerField(blank=True, null=True, verbose_name='What is the ID of the master conference?'),
        ),
    ]
