# Generated by Django 3.0.4 on 2020-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20200721_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='masterconfidfordaughter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='daughterconf',
            field=models.BooleanField(default=False, verbose_name='Or are you creating a session for a master conference that has already been created?'),
        ),
    ]
