# Generated by Django 3.0.4 on 2020-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_auto_20200721_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='payingatonce',
            field=models.BooleanField(default=False, verbose_name='Is the payment centralized to the master conference (or each session should pay on their own)?'),
        ),
    ]
