# Generated by Django 3.0.4 on 2020-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_createconf_payingatonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='masterconfdaughtername',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='createconf',
            name='masterconfdaughterposition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
