# Generated by Django 3.0.4 on 2020-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_auto_20200723_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='guidelines',
            field=models.TextField(default='e', verbose_name='Guidelines for your participants'),
            preserve_default=False,
        ),
    ]
