# Generated by Django 3.0.4 on 2020-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_website_guidelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='whorecording',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only conference participants', 'Only conference participants')], default='Everyone', max_length=50, verbose_name='Who can see the recording?'),
        ),
    ]
