# Generated by Django 3.0.4 on 2020-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_createconf_messagetoall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='messagetoall',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Message to all participants'),
        ),
    ]
