# Generated by Django 3.0.4 on 2020-10-15 09:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_auto_20201013_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='color_background',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
