# Generated by Django 3.0.4 on 2020-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_auto_20201015_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.IntegerField(choices=[(6, 'Talk'), (1, 'Invited Talk'), (2, 'Discussion'), (3, 'Review'), (4, 'Poster'), (5, 'Attendance only'), (7, 'Pause')], default=6, verbose_name='Oral type'),
        ),
    ]
