# Generated by Django 3.0.4 on 2020-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_auto_20201022_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='datetest',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registerconf',
            name='idconftest',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
