# Generated by Django 3.0.4 on 2020-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0037_auto_20201022_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerconf',
            name='idconf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registerconf',
            name='idconftest',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
