# Generated by Django 3.0.4 on 2020-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0041_createconf_privpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='privpass',
            field=models.CharField(default='', max_length=50),
        ),
    ]
