# Generated by Django 3.0.4 on 2020-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_createconf_twitterhashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, verbose_name='Orcid ID'),
        ),
    ]
