# Generated by Django 3.0.4 on 2020-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_createconf_acceptconf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='privpass',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
