# Generated by Django 3.0.4 on 2020-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0046_auto_20201129_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='dialin_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='createconf',
            name='dialin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='createconf',
            name='dialin_passcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='createconf',
            name='dialin_passcode_presenter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
