# Generated by Django 3.0.4 on 2020-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0047_auto_20201130_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='passzoom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
