# Generated by Django 3.0.4 on 2020-12-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0048_createvisio_passzoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='joinurlzoom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='starturlzoom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
