# Generated by Django 3.0.4 on 2020-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0049_auto_20201208_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='roomtype',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Big Marker', 'Big Marker')], default='Zoom', max_length=50, verbose_name='Which virtual room you want?'),
        ),
    ]
