# Generated by Django 3.0.4 on 2020-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0050_createconf_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createvisio',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='joinurlzoom',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='mp4_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='recidconf',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='starturlzoom',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='vimeo_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
