# Generated by Django 3.0.4 on 2020-12-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0051_auto_20201210_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='recend',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='recstart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='rectitles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
