# Generated by Django 3.0.4 on 2020-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0052_auto_20201211_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createvisio',
            name='celery_task_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='mp4_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='recend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='recidconf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='recstart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createvisio',
            name='vimeo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
