# Generated by Django 3.0.4 on 2020-12-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0053_auto_20201212_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerconf',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='registerconf',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Tell to the organizers about you'),
        ),
        migrations.AlterField(
            model_name='registerconf',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Title'),
        ),
    ]
