# Generated by Django 3.0.4 on 2021-01-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0057_createquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquestion',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonymous?'),
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='question',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
    ]
