# Generated by Django 3.0.4 on 2021-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0058_auto_20210102_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
