# Generated by Django 3.0.4 on 2021-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0059_createquestion_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
