# Generated by Django 3.0.4 on 2021-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0061_createconf_question_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestion',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
