# Generated by Django 3.0.4 on 2021-01-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0064_choicepoll_createpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupdateq',
            name='poll_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
