# Generated by Django 3.0.4 on 2021-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0066_remove_choicepoll_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
