# Generated by Django 3.0.4 on 2021-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0068_createpoll_showres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
