# Generated by Django 3.0.4 on 2021-01-13 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0069_userprofileinfo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicepoll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
