# Generated by Django 3.0.4 on 2021-02-05 10:28

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0070_choicepoll_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='color_menu',
            field=colorfield.fields.ColorField(default='#223', max_length=18, verbose_name='Menu color on the conference website'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='abstract',
            field=models.TextField(max_length=3000, verbose_name='Conference abstract'),
        ),
    ]
