# Generated by Django 3.0.4 on 2021-02-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0073_auto_20210205_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='color_menu',
            new_name='color_men',
        ),
    ]
