# Generated by Django 3.0.4 on 2021-02-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0074_auto_20210205_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='color_men',
        ),
    ]
