# Generated by Django 3.0.4 on 2021-02-10 09:03

import conf.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0077_createconf_parsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestion',
            name='pollimage',
            field=models.ImageField(blank=True, null=True, storage=conf.storage_backends.PublicMediaStorage(), upload_to='static/pollimages/', verbose_name=''),
        ),
    ]
