# Generated by Django 3.0.4 on 2021-02-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0080_createpoll_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='codeactive',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
