# Generated by Django 3.0.4 on 2021-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0081_auto_20210210_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
