# Generated by Django 3.0.4 on 2021-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0083_auto_20210210_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
