# Generated by Django 3.0.4 on 2021-02-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0084_auto_20210211_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
