# Generated by Django 3.0.4 on 2021-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0086_createconf_submitparticipations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='lastlogintimepanel',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
