# Generated by Django 3.0.4 on 2021-02-13 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0088_auto_20210213_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='lastlogintimepanel',
        ),
        migrations.CreateModel(
            name='UserUpdateL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastlogintimepanel', models.DateTimeField(blank=True, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.CreateConf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
