# Generated by Django 3.0.4 on 2021-02-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0089_auto_20210213_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='daughterconfstarwars',
            field=models.BooleanField(default=False, verbose_name="Do you want the daughter conferences to be named using some of famous Star wars planets' names?"),
        ),
    ]
