# Generated by Django 3.0.4 on 2021-02-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0090_createconf_daughterconfstarwars'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='subtomastautomatic',
            field=models.BooleanField(default=False, verbose_name='Should participants be automatically added to the master session (plenaries) when they get a participation accepted?'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='daughterconfstarwars',
            field=models.BooleanField(default=False, verbose_name="Do you want the daughter conferences to be named using some of the famous Star wars planets' names?"),
        ),
    ]
