# Generated by Django 3.0.4 on 2021-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0091_auto_20210215_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpeople',
            name='all',
            field=models.BooleanField(default=False, verbose_name='Send the message to participants from all sessions of the conference? (to click before the "who to" selection)'),
        ),
    ]
