# Generated by Django 3.0.4 on 2021-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0097_auto_20210227_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='fee_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fee they must pay'),
        ),
    ]
