# Generated by Django 3.0.4 on 2021-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0100_auto_20210228_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='zoomcreator',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
