# Generated by Django 3.0.4 on 2021-03-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0101_createvisio_zoomcreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='forgotpass',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
