# Generated by Django 3.0.4 on 2021-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0102_userprofileinfo_forgotpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='size',
            field=models.CharField(choices=[('<10', '<10 people'), ('10-50', '10-50 people'), ('50-100', '50-100 people'), ('100-300', '100-300 people'), ('300-500', '300-500 people'), ('500-1000', '500-1000 people')], default='50-100', max_length=9, verbose_name='Conference size'),
        ),
    ]
