# Generated by Django 3.0.4 on 2021-04-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0103_auto_20210311_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.IntegerField(default=0)),
                ('timefinish', models.IntegerField(default=24)),
                ('mineventheight', models.IntegerField(default=100)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.CreateConf')),
            ],
        ),
    ]
