# Generated by Django 3.0.4 on 2021-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0104_programdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdesign',
            name='heighthr',
            field=models.IntegerField(default=2, verbose_name='Height for each hour slot'),
        ),
        migrations.AlterField(
            model_name='programdesign',
            name='mineventheight',
            field=models.IntegerField(default=100, verbose_name='Minimum height of schedule boxes'),
        ),
        migrations.AlterField(
            model_name='programdesign',
            name='timefinish',
            field=models.IntegerField(default=24, verbose_name='End time of schedule span'),
        ),
        migrations.AlterField(
            model_name='programdesign',
            name='timestart',
            field=models.IntegerField(default=0, verbose_name='Start time of schedule span'),
        ),
    ]
