# Generated by Django 3.0.4 on 2021-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0105_auto_20210414_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdesign',
            name='minieventtime',
            field=models.IntegerField(default=10, verbose_name='Under how many minutes does it switch to the mini format?'),
        ),
        migrations.AddField(
            model_name='programdesign',
            name='opacity',
            field=models.IntegerField(default=1, verbose_name='Opacity of the boxes'),
        ),
    ]
