# Generated by Django 3.0.4 on 2021-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0107_auto_20210421_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notpart',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
