# Generated by Django 3.0.4 on 2021-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0108_schedule_notpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='fastpass',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
