# Generated by Django 3.0.4 on 2021-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0109_createconf_fastpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='submitparticipations',
            field=models.BooleanField(default=True, verbose_name='Can the participants submit presentations?'),
        ),
        migrations.AlterField(
            model_name='transac',
            name='customerid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
