# Generated by Django 3.0.4 on 2021-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0110_auto_20210504_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='customerid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
