# Generated by Django 3.0.4 on 2021-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0111_auto_20210504_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='transac',
            name='transaccreated',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transac',
            name='validatedwebhook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
