# Generated by Django 3.0.4 on 2021-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0119_statsmaster_nbattonlynonaccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='closing_date',
            field=models.DateField(null=True),
        ),
    ]
