# Generated by Django 3.0.4 on 2021-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0120_createconf_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
