# Generated by Django 3.0.4 on 2021-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0121_auto_20210526_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='activateqandp',
            field=models.BooleanField(default=True, verbose_name='Activate the questions and polls during the conference?'),
        ),
    ]
