# Generated by Django 3.0.4 on 2021-06-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0125_auto_20210610_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsmaster',
            name='bestposter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postervie', to='my_app.RegisterConf'),
        ),
        migrations.AddField(
            model_name='statsmaster',
            name='view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statsmaster',
            name='view2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statsmaster',
            name='votes2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statsmaster',
            name='bestposter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bestposter', to='my_app.RegisterConf'),
        ),
    ]
