# Generated by Django 3.0.4 on 2021-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0126_auto_20210610_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='rights',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
