# Generated by Django 3.0.4 on 2021-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0127_createvisio_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createvisio',
            name='rights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
