# Generated by Django 3.0.4 on 2021-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0128_auto_20210614_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='updateactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
