# Generated by Django 3.0.4 on 2021-06-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0129_createpoll_updateactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='instcountry',
            field=models.CharField(max_length=200, null=True, verbose_name='Country of Institute/Company'),
        ),
    ]
