# Generated by Django 3.0.4 on 2021-07-08 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0133_auto_20210708_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='minleftmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
