# Generated by Django 3.0.4 on 2021-07-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0134_minleftmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minleftmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
