# Generated by Django 3.0.4 on 2021-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0135_auto_20210708_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='minleftmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='minleftmodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
