# Generated by Django 3.0.4 on 2021-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0136_auto_20210709_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minleftmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='createconf',
            name='minleftcreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
