# Generated by Django 3.0.4 on 2021-07-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0137_auto_20210709_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='minleftuserfln',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
