# Generated by Django 3.0.4 on 2021-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0140_auto_20210719_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='celery_task_id_fin_cb',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='idconfcb',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='joinurlzoomcb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='passzoomcb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createvisio',
            name='starturlzoomcb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
