# Generated by Django 3.0.4 on 2021-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0141_auto_20210719_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='hybrid',
            field=models.BooleanField(default=False, verbose_name='Is the conference hybrid (i.e. both face-to-face and virtual)?'),
        ),
        migrations.AlterField(
            model_name='website',
            name='onlypprogram',
            field=models.BooleanField(default=False, verbose_name='Program and Timeline showed only to validated participants?'),
        ),
        migrations.AlterField(
            model_name='website',
            name='showprogram',
            field=models.BooleanField(default=False, verbose_name='Program and Timeline ready to be displayed on the conference website?'),
        ),
    ]
