# Generated by Django 3.0.4 on 2021-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0143_auto_20210824_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerconf',
            name='facetoface',
            field=models.BooleanField(default=False, verbose_name='Will you come in person to the conference? (if you assist virtually select No)'),
        ),
    ]
