# Generated by Django 3.0.4 on 2021-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0145_auto_20210824_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerconf',
            name='facetoface',
            field=models.BooleanField(default=False, verbose_name='Will you come in person to the hybrid conference? (if you assist virtually do not tick the box)'),
        ),
    ]
