# Generated by Django 3.0.4 on 2021-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0149_auto_20210825_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='onlypdoc',
            field=models.BooleanField(default=False, verbose_name='Documents only accessible to validated participants?'),
        ),
    ]
