# Generated by Django 3.0.4 on 2021-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0150_website_onlypdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerconf',
            name='mp4show',
            field=models.BooleanField(default=False),
        ),
    ]
