# Generated by Django 3.0.4 on 2021-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0151_registerconf_mp4show'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='feeunique',
            field=models.BooleanField(default=False, verbose_name='Share the conference fees between everyone by choosing a unique 20€ fee per person (it includes everything and we also offset the carbon emissions)'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='fee',
            field=models.BooleanField(default=False, verbose_name='Pay the conferences fees but get money back from participants?'),
        ),
        migrations.AlterField(
            model_name='registerconf',
            name='paperurl',
            field=models.URLField(blank=True, max_length=300, verbose_name=''),
        ),
    ]
