# Generated by Django 3.0.4 on 2021-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0152_auto_20210825_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='feeunique',
            field=models.BooleanField(default=False, verbose_name='Share the conference fees between everyone by choosing a unique 20€ fee per person (it includes everything such as technical support and we also offset the carbon emissions)'),
        ),
    ]
