# Generated by Django 3.0.4 on 2021-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0153_auto_20210825_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='fee_currency_unique',
            field=models.CharField(choices=[('Euros', 'Euros'), ('US Dollars', 'US Dollars'), ('GB Pounds', 'GB Pounds')], default='Euros', max_length=15, verbose_name='Choose the currency of most participantss that will be proposed by default'),
        ),
    ]
