# Generated by Django 3.0.4 on 2021-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0156_auto_20210827_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='fee_amount_unique',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='feeunique',
            field=models.BooleanField(default=False, verbose_name='Share the conference fees between everyone by choosing a unique fee per person (it includes everything such as technical support and we also offset the carbon emissions)'),
        ),
    ]
