# Generated by Django 3.0.4 on 2021-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0157_auto_20210827_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='justtools',
            field=models.BooleanField(default=False, verbose_name='We will just use the tools for free and not run the conference with CarbonFreeConf (it can be changed later)'),
        ),
    ]
