# Generated by Django 3.0.4 on 2021-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0158_createconf_justtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='justtools',
            field=models.BooleanField(default=False, verbose_name='We will just use the CarbonFreeConf tools (e.g. abstract management, website creation, participant and program handling, ...) for free and not run the conference with CarbonFreeConf'),
        ),
    ]
