# Generated by Django 3.0.4 on 2021-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0161_auto_20210921_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvisio',
            name='zoomcreatorcb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
