# Generated by Django 3.0.3 on 2022-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0162_createvisio_zoomcreatorcb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconf',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Conference titl'),
        ),
    ]
