# Generated by Django 3.0.4 on 2022-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0163_auto_20220320_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='titleurl',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closing date'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='createconf',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Conference title'),
        ),
    ]
