# Generated by Django 3.0.4 on 2022-06-29 09:22

import conf.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0167_auto_20220625_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroimages', models.ImageField(blank=True, null=True, storage=conf.storage_backends.PublicMediaStorage(), upload_to='static/heroimages/', verbose_name='')),
            ],
        ),
    ]
