# Generated by Django 3.0.4 on 2022-06-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0168_heropicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.HeroPicture'),
        ),
    ]
