# Generated by Django 3.0.4 on 2022-06-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0170_auto_20220629_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.HeroPicture', verbose_name='Hero image'),
        ),
    ]
