# Generated by Django 3.0.4 on 2022-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0171_auto_20220629_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropicture',
            name='heroname',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Name of hero image'),
        ),
    ]
