# Generated by Django 3.0.4 on 2022-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0173_remove_website_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconf',
            name='title_extra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
