# Generated by Django 3.0.4 on 2020-11-20 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201120_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postview',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
