# Generated by Django 3.0.4 on 2020-11-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201120_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='num',
            new_name='number',
        ),
    ]
