# Generated by Django 3.0.4 on 2021-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_question_confid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='confid',
            field=models.IntegerField(default=0),
        ),
    ]
